export default [
  {
    id: 1,
    name: "Sekiro: Shadows Die Once",
    description:
      "A samurai action-adventure game where players control a shinobi on a quest to rescue his kidnapped lord and seek revenge on his enemies.",
    category: "Action",
    price: 59.99,
    discount: true,
    discountPercent: 25,
    priceFrom: 70,
    star: 5,
    platforms: {
      playstation: true,
      xbox: true,
      nintendo: true,
      pc: true,
    },
    languages: ["English", "Japanese", "French", "German", "Spanish"],
    releaseDate: "2019-03-22",
    playableOn: ["PS5", "PS4", "Xbox One", "PC"],
    editions: {
      deluxe: 79.99,
      complete: 89.99,
      ultimate: 99.99,
    },
    productKey: true,
    available: true,
    stock: 100,
    tags: ["action", "adventure", "samurai"],
    brand: "FromSoftware",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "An amazing combat experience and a challenging journey.",
        date: "2024-11-25T11:00:00Z",
        reviewerName: "Takashi Yamada",
        reviewerEmail: "takashi.yamada@example.com",
      },
    ],
    thumbnail: "/forza.jpg",
    images: [
      "https://example.com/images/sekiro-1.jpg",
      "https://example.com/images/sekiro-2.jpg",
    ],
  },
  {
    id: 2,
    name: "Ghostrunner",
    description:
      "A high-speed action game set in a cyberpunk world where players take on the role of a cybernetic ninja fighting through futuristic cityscapes.",
    category: "Action",
    price: 79.99,
    discount: true,
    discountPercent: 25,
    priceFrom: 50,
    star: 4,
    platforms: {
      playstation: true,
      xbox: false,
      nintendo: false,
      pc: true,
    },
    languages: ["English", "Spanish", "French", "German"],
    releaseDate: "2020-10-27",
    playableOn: ["PS5", "PS4", "PC"],
    editions: {
      deluxe: 89.99,
      complete: 109.99,
      ultimate: 129.99,
    },
    productKey: false,
    available: true,
    stock: 150,
    tags: ["cyberpunk", "action", "stealth"],
    brand: "One More Level",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Fast-paced action and a unique setting.",
        date: "2024-11-22T15:00:00Z",
        reviewerName: "Chris Mendez",
        reviewerEmail: "chris.mendez@example.com",
      },
    ],
    thumbnail: "https://example.com/images/ghostrunner-thumbnail.jpg",
    images: [
      "https://example.com/images/ghostrunner-1.jpg",
      "https://example.com/images/ghostrunner-2.jpg",
    ],
  },
  {
    id: 3,
    name: "Forza Horizon 6",
    description:
      "An open-world racing game that lets players race across beautiful landscapes, from city streets to sprawling countryside.",
    category: "Racing",
    price: 55.99,
    discount: true,
    discountPercent: 25,
    priceFrom: 40,
    star: 5,
    platforms: {
      playstation: false,
      xbox: true,
      nintendo: true,
      pc: true,
    },
    languages: ["English", "Spanish", "Italian", "German"],
    releaseDate: "2024-10-01",
    playableOn: ["Xbox Series X/S", "PC", "Nintendo Switch"],
    editions: {
      deluxe: 69.99,
      complete: 89.99,
      ultimate: 119.99,
    },
    productKey: true,
    available: true,
    stock: 200,
    tags: ["racing", "open-world", "driving"],
    brand: "Playground Games",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Best racing experience ever!",
        date: "2024-11-23T14:00:00Z",
        reviewerName: "Mark Davis",
        reviewerEmail: "mark.davis@example.com",
      },
    ],
    thumbnail: "https://example.com/images/forza-horizon-6-thumbnail.jpg",
    images: [
      "https://example.com/images/forza-horizon-6-1.jpg",
      "https://example.com/images/forza-horizon-6-2.jpg",
    ],
  },
  {
    id: 4,
    name: "Far Cry 6",
    description:
      "A first-person shooter set in the fictional country of Yara, inspired by Cuba, where players must fight to overthrow a dictator.",
    category: "Shooter",
    price: 69.99,
    discount: false,
    discountPercent: 25,
    priceFrom: 65,
    star: 3,
    platforms: {
      playstation: true,
      xbox: false,
      nintendo: true,
      pc: true,
    },
    languages: ["English", "French", "German", "Spanish", "Italian"],
    releaseDate: "2021-10-07",
    playableOn: ["PS5", "PS4", "PC"],
    editions: {
      deluxe: 79.99,
      complete: 99.99,
      ultimate: 129.99,
    },
    productKey: false,
    available: true,
    stock: 50,
    tags: ["shooter", "open-world", "action"],
    brand: "Ubisoft",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 3,
        comment: "Good gameplay, but not as impactful as previous entries.",
        date: "2024-11-19T16:00:00Z",
        reviewerName: "Liam O'Connor",
        reviewerEmail: "liam.oconnor@example.com",
      },
    ],
    thumbnail: "https://example.com/images/farcry6-thumbnail.jpg",
    images: [
      "https://example.com/images/farcry6-1.jpg",
      "https://example.com/images/farcry6-2.jpg",
    ],
  },
  {
    id: 5,
    name: "Cyberpunk 2077",
    description:
      "An open-world, action-adventure story set in Night City, a megalopolis obsessed with power, glamour, and body modification.",
    category: "RPG",
    price: 59.99,
    discount: true,
    discountPercent: 15,
    priceFrom: 69.99,
    star: 4.5,
    platforms: {
      playstation: true,
      xbox: true,
      nintendo: false,
      pc: true,
    },
    languages: ["English", "Spanish", "French", "German", "Japanese"],
    releaseDate: "2020-12-10",
    playableOn: ["PS5", "PS4", "Xbox Series X/S", "PC"],
    editions: {
      deluxe: 79.99,
      complete: 99.99,
      ultimate: 119.99,
    },
    productKey: true,
    available: true,
    stock: 120,
    tags: ["open-world", "sci-fi", "action"],
    brand: "CD Projekt Red",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Fantastic game with stunning visuals!",
        date: "2024-11-28T12:00:00Z",
        reviewerName: "Alex Mercer",
        reviewerEmail: "alex.mercer@example.com",
      },
    ],
    thumbnail: "https://example.com/images/cyberpunk2077-thumbnail.jpg",
    images: [
      "https://example.com/images/cyberpunk2077-1.jpg",
      "https://example.com/images/cyberpunk2077-2.jpg",
    ],
  },
  {
    id: 6,
    name: "The Legend of Zelda: Tears of the Kingdom",
    description: "The epic sequel to The Legend of Zelda: Breath of the Wild.",
    category: "Adventure",
    price: 69.99,
    discount: false,
    discountPercent: 0,
    priceFrom: null,
    star: 5,
    platforms: {
      playstation: false,
      xbox: false,
      nintendo: true,
      pc: false,
    },
    languages: ["English", "Japanese", "Korean", "Spanish", "French"],
    releaseDate: "2023-05-12",
    playableOn: ["Nintendo Switch"],
    editions: {
      deluxe: 89.99,
      complete: 109.99,
      ultimate: 129.99,
    },
    productKey: false,
    available: true,
    stock: 80,
    tags: ["open-world", "adventure", "fantasy"],
    brand: "Nintendo",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4.5,
        comment: "A breathtaking sequel that expands on the original.",
        date: "2024-11-20T14:00:00Z",
        reviewerName: "Sam Ryder",
        reviewerEmail: "sam.ryder@example.com",
      },
    ],
    thumbnail: "https://example.com/images/zelda-totk-thumbnail.jpg",
    images: [
      "https://example.com/images/zelda-totk-1.jpg",
      "https://example.com/images/zelda-totk-2.jpg",
    ],
  },
  {
    id: 7,
    name: "Elden Ring",
    description: "A vast world full of excitement with a rich and dark story.",
    category: "Action RPG",
    price: 59.99,
    discount: true,
    discountPercent: 10,
    priceFrom: 66.99,
    star: 4.8,
    platforms: {
      playstation: true,
      xbox: true,
      nintendo: false,
      pc: true,
    },
    languages: ["English", "Chinese", "Russian", "German", "French"],
    releaseDate: "2022-02-25",
    playableOn: ["PS5", "PS4", "Xbox Series X/S", "Xbox One", "PC"],
    editions: {
      deluxe: 79.99,
      complete: 99.99,
      ultimate: 129.99,
    },
    productKey: true,
    available: false,
    stock: 0,
    tags: ["dark-fantasy", "exploration", "combat"],
    brand: "FromSoftware",
    availabilityStatus: "Out of Stock",
    reviews: [
      {
        rating: 5,
        comment: "A masterpiece in every way!",
        date: "2024-11-15T18:00:00Z",
        reviewerName: "Jordan Lee",
        reviewerEmail: "jordan.lee@example.com",
      },
    ],
    thumbnail: "https://example.com/images/elden-ring-thumbnail.jpg",
    images: [
      "https://example.com/images/elden-ring-1.jpg",
      "https://example.com/images/elden-ring-2.jpg",
    ],
  },
  {
    id: 8,
    name: "Grand Theft Auto V",
    description:
      "A bold new direction in open-world freedom, storytelling, and mission-based gameplay.",
    category: "Action",
    price: 29.99,
    discount: true,
    discountPercent: 25,
    priceFrom: 39.99,
    star: 4.7,
    platforms: {
      playstation: true,
      xbox: true,
      nintendo: false,
      pc: true,
    },
    languages: ["English", "Spanish", "French", "German", "Italian"],
    releaseDate: "2013-09-17",
    playableOn: ["PS5", "PS4", "Xbox Series X/S", "Xbox One", "PC"],
    editions: {
      deluxe: 49.99,
      complete: 69.99,
      ultimate: 89.99,
    },
    productKey: true,
    available: true,
    stock: 200,
    tags: ["open-world", "crime", "adventure"],
    brand: "Rockstar Games",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Great story and gameplay!",
        date: "2024-11-10T16:00:00Z",
        reviewerName: "Chris Pine",
        reviewerEmail: "chris.pine@example.com",
      },
    ],
    thumbnail: "https://example.com/images/gta-v-thumbnail.jpg",
    images: [
      "https://example.com/images/gta-v-1.jpg",
      "https://example.com/images/gta-v-2.jpg",
    ],
  },
  {
    id: 9,
    name: "Horizon Forbidden West",
    description:
      "Explore distant lands, fight bigger and more awe-inspiring machines, and encounter astonishing new tribes.",
    category: "Adventure",
    price: 69.99,
    discount: false,
    discountPercent: 0,
    priceFrom: null,
    star: 4.9,
    platforms: {
      playstation: true,
      xbox: false,
      nintendo: false,
      pc: true,
    },
    languages: ["English", "Spanish", "French", "German"],
    releaseDate: "2022-02-18",
    playableOn: ["PS5", "PS4", "PC"],
    editions: {
      deluxe: 89.99,
      complete: 109.99,
      ultimate: 129.99,
    },
    productKey: true,
    available: true,
    stock: 150,
    tags: ["open-world", "exploration", "action"],
    brand: "Guerrilla Games",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "A visual and storytelling masterpiece!",
        date: "2024-11-05T10:00:00Z",
        reviewerName: "Emma Watson",
        reviewerEmail: "emma.watson@example.com",
      },
    ],
    thumbnail: "https://example.com/images/horizon-fw-thumbnail.jpg",
    images: [
      "https://example.com/images/horizon-fw-1.jpg",
      "https://example.com/images/horizon-fw-2.jpg",
    ],
  },
  {
    id: 10,
    name: "Red Dead Redemption 2",
    description: "An epic tale of life in America’s unforgiving heartland.",
    category: "Adventure",
    price: 49.99,
    discount: true,
    discountPercent: 20,
    priceFrom: 62.49,
    star: 5,
    platforms: {
      playstation: true,
      xbox: true,
      nintendo: false,
      pc: true,
    },
    languages: ["English", "Spanish", "Portuguese", "French", "Italian"],
    releaseDate: "2018-10-26",
    playableOn: ["PS5", "PS4", "Xbox Series X/S", "Xbox One", "PC"],
    editions: {
      deluxe: 69.99,
      complete: 89.99,
      ultimate: 119.99,
    },
    productKey: true,
    available: true,
    stock: 50,
    tags: ["western", "open-world", "story-driven"],
    brand: "Rockstar Games",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "An unforgettable experience.",
        date: "2024-11-01T08:00:00Z",
        reviewerName: "John Marston",
        reviewerEmail: "john.marston@example.com",
      },
    ],
    thumbnail: "https://example.com/images/rdr2-thumbnail.jpg",
    images: [
      "https://example.com/images/rdr2-1.jpg",
      "https://example.com/images/rdr2-2.jpg",
    ],
  },
];
