export default [
  {
    name: "Sekiro: Shadows Die Once",
    description:
      "A samurai action-adventure game where players control a shinobi on a quest to rescue his kidnapped lord and seek revenge on his enemies.",
    category: "Action",
    price: 59.99,
    discount: true,
    discountPercent: 25,
    priceFrom: 70,
    star: 5,
    platforms: {
      playstation: true,
      xbox: true,
      nintendo: true,
      pc: true,
    },
    languages: ["English", "Japanese", "French", "German", "Spanish"],
    releaseDate: "2019-03-22",
    playableOn: ["PS5", "PS4", "Xbox One", "PC"],
    editions: {
      deluxe: 79.99,
      complete: 89.99,
      ultimate: 99.99,
    },
    productKey: true,
    available: true,
    stock: 100,
    tags: ["action", "adventure", "samurai"],
    brand: "FromSoftware",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "An amazing combat experience and a challenging journey.",
        date: "2024-11-25T11:00:00Z",
        reviewerName: "Takashi Yamada",
        reviewerEmail: "takashi.yamada@example.com",
      },
    ],
    thumbnail: "/seikro.png",
    images: [
      "/public/seikro1.jpg",
      "/public/seikro2.jpg",
      "/public/seikro3.jpg",
    ],
    video: "https://youtu.be/a2TjEl0l_FU?si=ZcjVkMnlUlnkdQC7",
  },
  {
    name: "Ghostrunner",
    description:
      "A high-speed action game set in a cyberpunk world where players take on the role of a cybernetic ninja fighting through futuristic cityscapes.",
    category: "Action",
    price: 79.99,
    discount: true,
    discountPercent: 25,
    priceFrom: 50,
    star: 4,
    platforms: {
      playstation: true,
      xbox: false,
      nintendo: false,
      pc: true,
    },
    languages: ["English", "Spanish", "French", "German"],
    releaseDate: "2020-10-27",
    playableOn: ["PS5", "PS4", "PC"],
    editions: {
      deluxe: 89.99,
      complete: 109.99,
      ultimate: 129.99,
    },
    productKey: false,
    available: true,
    stock: 150,
    tags: ["cyberpunk", "action", "stealth"],
    brand: "One More Level",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Fast-paced action and a unique setting.",
        date: "2024-11-22T15:00:00Z",
        reviewerName: "Chris Mendez",
        reviewerEmail: "chris.mendez@example.com",
      },
    ],
    thumbnail: "/ghostRunner.png",
    images: ["/ghostRunner1.jpg", "/ghostRunner2.jpg", "/ghostRunner3.jpg"],
  },
  {
    name: "Forza Horizon 6",
    description:
      "An open-world racing game that lets players race across beautiful landscapes, from city streets to sprawling countryside.",
    category: "Racing",
    price: 55.99,
    discount: true,
    discountPercent: 25,
    priceFrom: 40,
    star: 5,
    platforms: {
      playstation: false,
      xbox: true,
      nintendo: true,
      pc: true,
    },
    languages: ["English", "Spanish", "Italian", "German"],
    releaseDate: "2024-10-01",
    playableOn: ["Xbox Series X/S", "PC", "Nintendo Switch"],
    editions: {
      deluxe: 69.99,
      complete: 89.99,
      ultimate: 119.99,
    },
    productKey: true,
    available: true,
    stock: 200,
    tags: ["racing", "open-world", "driving"],
    brand: "Playground Games",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Best racing experience ever!",
        date: "2024-11-23T14:00:00Z",
        reviewerName: "Mark Davis",
        reviewerEmail: "mark.davis@example.com",
      },
    ],
    thumbnail: "/forza.jpg",
    images: [
      "/forza1.jpg",
      "/forza2.jpg",
      "/forza3.jpg",
    ],
  },
  {
    name: "Ghostrunner",
    description:
      "A high-speed action game set in a cyberpunk world where players take on the role of a cybernetic ninja fighting through futuristic cityscapes.",
    category: "Action",
    price: 79.99,
    discount: true,
    discountPercent: 25,
    priceFrom: 50,
    star: 4,
    platforms: {
      playstation: true,
      xbox: false,
      nintendo: false,
      pc: true,
    },
    languages: ["English", "Spanish", "French", "German"],
    releaseDate: "2020-10-27",
    playableOn: ["PS5", "PS4", "PC"],
    editions: {
      deluxe: 89.99,
      complete: 109.99,
      ultimate: 129.99,
    },
    productKey: false,
    available: true,
    stock: 150,
    tags: ["cyberpunk", "action", "stealth"],
    brand: "One More Level",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Fast-paced action and a unique setting.",
        date: "2024-11-22T15:00:00Z",
        reviewerName: "Chris Mendez",
        reviewerEmail: "chris.mendez@example.com",
      },
    ],
    thumbnail: "/ghostRunner.png",
    images: ["/ghostRunner1.jpg", "/ghostRunner2.jpg", "/ghostRunner3.jpg"],
  },
  {
    name: "Forza Horizon 6",
    description:
      "An open-world racing game that lets players race across beautiful landscapes, from city streets to sprawling countryside.",
    category: "Racing",
    price: 55.99,
    discount: true,
    discountPercent: 25,
    priceFrom: 40,
    star: 5,
    platforms: {
      playstation: false,
      xbox: true,
      nintendo: true,
      pc: true,
    },
    languages: ["English", "Spanish", "Italian", "German"],
    releaseDate: "2024-10-01",
    playableOn: ["Xbox Series X/S", "PC", "Nintendo Switch"],
    editions: {
      deluxe: 69.99,
      complete: 89.99,
      ultimate: 119.99,
    },
    productKey: true,
    available: true,
    stock: 200,
    tags: ["racing", "open-world", "driving"],
    brand: "Playground Games",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Best racing experience ever!",
        date: "2024-11-23T14:00:00Z",
        reviewerName: "Mark Davis",
        reviewerEmail: "mark.davis@example.com",
      },
    ],
    thumbnail: "/forza.jpg",
    images: [
      "/forza1.jpg",
      "/forza2.jpg",
      "/forza3.jpg",
    ],
  },
  {
    name: "Sekiro: Shadows Die Once",
    description:
      "A samurai action-adventure game where players control a shinobi on a quest to rescue his kidnapped lord and seek revenge on his enemies.",
    category: "Action",
    price: 59.99,
    discount: true,
    discountPercent: 25,
    priceFrom: 70,
    star: 5,
    platforms: {
      playstation: true,
      xbox: true,
      nintendo: true,
      pc: true,
    },
    languages: ["English", "Japanese", "French", "German", "Spanish"],
    releaseDate: "2019-03-22",
    playableOn: ["PS5", "PS4", "Xbox One", "PC"],
    editions: {
      deluxe: 79.99,
      complete: 89.99,
      ultimate: 99.99,
    },
    productKey: true,
    available: true,
    stock: 100,
    tags: ["action", "adventure", "samurai"],
    brand: "FromSoftware",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "An amazing combat experience and a challenging journey.",
        date: "2024-11-25T11:00:00Z",
        reviewerName: "Takashi Yamada",
        reviewerEmail: "takashi.yamada@example.com",
      },
    ],
    thumbnail: "/seikro.png",
    images: [
      "/public/seikro1.jpg",
      "/public/seikro2.jpg",
      "/public/seikro3.jpg",
    ],
    video: "https://youtu.be/a2TjEl0l_FU?si=ZcjVkMnlUlnkdQC7",
  },
  {
    name: "Ghostrunner",
    description:
      "A high-speed action game set in a cyberpunk world where players take on the role of a cybernetic ninja fighting through futuristic cityscapes.",
    category: "Action",
    price: 79.99,
    discount: true,
    discountPercent: 25,
    priceFrom: 50,
    star: 4,
    platforms: {
      playstation: true,
      xbox: false,
      nintendo: false,
      pc: true,
    },
    languages: ["English", "Spanish", "French", "German"],
    releaseDate: "2020-10-27",
    playableOn: ["PS5", "PS4", "PC"],
    editions: {
      deluxe: 89.99,
      complete: 109.99,
      ultimate: 129.99,
    },
    productKey: false,
    available: true,
    stock: 150,
    tags: ["cyberpunk", "action", "stealth"],
    brand: "One More Level",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Fast-paced action and a unique setting.",
        date: "2024-11-22T15:00:00Z",
        reviewerName: "Chris Mendez",
        reviewerEmail: "chris.mendez@example.com",
      },
    ],
    thumbnail: "/ghostRunner.png",
    images: ["/ghostRunner1.jpg", "/ghostRunner2.jpg", "/ghostRunner3.jpg"],
  },
  {
    name: "Forza Horizon 6",
    description:
      "An open-world racing game that lets players race across beautiful landscapes, from city streets to sprawling countryside.",
    category: "Racing",
    price: 55.99,
    discount: true,
    discountPercent: 25,
    priceFrom: 40,
    star: 5,
    platforms: {
      playstation: false,
      xbox: true,
      nintendo: true,
      pc: true,
    },
    languages: ["English", "Spanish", "Italian", "German"],
    releaseDate: "2024-10-01",
    playableOn: ["Xbox Series X/S", "PC", "Nintendo Switch"],
    editions: {
      deluxe: 69.99,
      complete: 89.99,
      ultimate: 119.99,
    },
    productKey: true,
    available: true,
    stock: 200,
    tags: ["racing", "open-world", "driving"],
    brand: "Playground Games",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Best racing experience ever!",
        date: "2024-11-23T14:00:00Z",
        reviewerName: "Mark Davis",
        reviewerEmail: "mark.davis@example.com",
      },
    ],
    thumbnail: "/forza.jpg",
    images: [
      "/forza1.jpg",
      "/forza2.jpg",
      "/forza3.jpg",
    ],
  },
  {
    name: "Ghostrunner",
    description:
      "A high-speed action game set in a cyberpunk world where players take on the role of a cybernetic ninja fighting through futuristic cityscapes.",
    category: "Action",
    price: 79.99,
    discount: true,
    discountPercent: 25,
    priceFrom: 50,
    star: 4,
    platforms: {
      playstation: true,
      xbox: false,
      nintendo: false,
      pc: true,
    },
    languages: ["English", "Spanish", "French", "German"],
    releaseDate: "2020-10-27",
    playableOn: ["PS5", "PS4", "PC"],
    editions: {
      deluxe: 89.99,
      complete: 109.99,
      ultimate: 129.99,
    },
    productKey: false,
    available: true,
    stock: 150,
    tags: ["cyberpunk", "action", "stealth"],
    brand: "One More Level",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Fast-paced action and a unique setting.",
        date: "2024-11-22T15:00:00Z",
        reviewerName: "Chris Mendez",
        reviewerEmail: "chris.mendez@example.com",
      },
    ],
    thumbnail: "/ghostRunner.png",
    images: ["/ghostRunner1.jpg", "/ghostRunner2.jpg", "/ghostRunner3.jpg"],
  },
  {
    name: "Forza Horizon 6",
    description:
      "An open-world racing game that lets players race across beautiful landscapes, from city streets to sprawling countryside.",
    category: "Racing",
    price: 55.99,
    discount: true,
    discountPercent: 25,
    priceFrom: 40,
    star: 5,
    platforms: {
      playstation: false,
      xbox: true,
      nintendo: true,
      pc: true,
    },
    languages: ["English", "Spanish", "Italian", "German"],
    releaseDate: "2024-10-01",
    playableOn: ["Xbox Series X/S", "PC", "Nintendo Switch"],
    editions: {
      deluxe: 69.99,
      complete: 89.99,
      ultimate: 119.99,
    },
    productKey: true,
    available: true,
    stock: 200,
    tags: ["racing", "open-world", "driving"],
    brand: "Playground Games",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Best racing experience ever!",
        date: "2024-11-23T14:00:00Z",
        reviewerName: "Mark Davis",
        reviewerEmail: "mark.davis@example.com",
      },
    ],
    thumbnail: "/forza.jpg",
    images: [
      "/forza1.jpg",
      "/forza2.jpg",
      "/forza3.jpg",
    ],
  },
  {
    name: "Sekiro: Shadows Die Once",
    description:
      "A samurai action-adventure game where players control a shinobi on a quest to rescue his kidnapped lord and seek revenge on his enemies.",
    category: "Action",
    price: 59.99,
    discount: true,
    discountPercent: 25,
    priceFrom: 70,
    star: 5,
    platforms: {
      playstation: true,
      xbox: true,
      nintendo: true,
      pc: true,
    },
    languages: ["English", "Japanese", "French", "German", "Spanish"],
    releaseDate: "2019-03-22",
    playableOn: ["PS5", "PS4", "Xbox One", "PC"],
    editions: {
      deluxe: 79.99,
      complete: 89.99,
      ultimate: 99.99,
    },
    productKey: true,
    available: true,
    stock: 100,
    tags: ["action", "adventure", "samurai"],
    brand: "FromSoftware",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "An amazing combat experience and a challenging journey.",
        date: "2024-11-25T11:00:00Z",
        reviewerName: "Takashi Yamada",
        reviewerEmail: "takashi.yamada@example.com",
      },
    ],
    thumbnail: "/seikro.png",
    images: [
      "/public/seikro1.jpg",
      "/public/seikro2.jpg",
      "/public/seikro3.jpg",
    ],
    video: "https://youtu.be/a2TjEl0l_FU?si=ZcjVkMnlUlnkdQC7",
  },
  {
    name: "Forza Horizon 6",
    description:
      "An open-world racing game that lets players race across beautiful landscapes, from city streets to sprawling countryside.",
    category: "Racing",
    price: 55.99,
    discount: true,
    discountPercent: 25,
    priceFrom: 40,
    star: 5,
    platforms: {
      playstation: false,
      xbox: true,
      nintendo: true,
      pc: true,
    },
    languages: ["English", "Spanish", "Italian", "German"],
    releaseDate: "2024-10-01",
    playableOn: ["Xbox Series X/S", "PC", "Nintendo Switch"],
    editions: {
      deluxe: 69.99,
      complete: 89.99,
      ultimate: 119.99,
    },
    productKey: true,
    available: true,
    stock: 200,
    tags: ["racing", "open-world", "driving"],
    brand: "Playground Games",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Best racing experience ever!",
        date: "2024-11-23T14:00:00Z",
        reviewerName: "Mark Davis",
        reviewerEmail: "mark.davis@example.com",
      },
    ],
    thumbnail: "/forza.jpg",
    images: [
      "/forza1.jpg",
      "/forza2.jpg",
      "/forza3.jpg",
    ],
  },
  {
    name: "Ghostrunner",
    description:
      "A high-speed action game set in a cyberpunk world where players take on the role of a cybernetic ninja fighting through futuristic cityscapes.",
    category: "Action",
    price: 79.99,
    discount: true,
    discountPercent: 25,
    priceFrom: 50,
    star: 4,
    platforms: {
      playstation: true,
      xbox: false,
      nintendo: false,
      pc: true,
    },
    languages: ["English", "Spanish", "French", "German"],
    releaseDate: "2020-10-27",
    playableOn: ["PS5", "PS4", "PC"],
    editions: {
      deluxe: 89.99,
      complete: 109.99,
      ultimate: 129.99,
    },
    productKey: false,
    available: true,
    stock: 150,
    tags: ["cyberpunk", "action", "stealth"],
    brand: "One More Level",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Fast-paced action and a unique setting.",
        date: "2024-11-22T15:00:00Z",
        reviewerName: "Chris Mendez",
        reviewerEmail: "chris.mendez@example.com",
      },
    ],
    thumbnail: "/ghostRunner.png",
    images: ["/ghostRunner1.jpg", "/ghostRunner2.jpg", "/ghostRunner3.jpg"],
  },
  {
    name: "Forza Horizon 6",
    description:
      "An open-world racing game that lets players race across beautiful landscapes, from city streets to sprawling countryside.",
    category: "Racing",
    price: 55.99,
    discount: true,
    discountPercent: 25,
    priceFrom: 40,
    star: 5,
    platforms: {
      playstation: false,
      xbox: true,
      nintendo: true,
      pc: true,
    },
    languages: ["English", "Spanish", "Italian", "German"],
    releaseDate: "2024-10-01",
    playableOn: ["Xbox Series X/S", "PC", "Nintendo Switch"],
    editions: {
      deluxe: 69.99,
      complete: 89.99,
      ultimate: 119.99,
    },
    productKey: true,
    available: true,
    stock: 200,
    tags: ["racing", "open-world", "driving"],
    brand: "Playground Games",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Best racing experience ever!",
        date: "2024-11-23T14:00:00Z",
        reviewerName: "Mark Davis",
        reviewerEmail: "mark.davis@example.com",
      },
    ],
    thumbnail: "/forza.jpg",
    images: [
      "/forza1.jpg",
      "/forza2.jpg",
      "/forza3.jpg",
    ],
  },
  {
    name: "Sekiro: Shadows Die Once",
    description:
      "A samurai action-adventure game where players control a shinobi on a quest to rescue his kidnapped lord and seek revenge on his enemies.",
    category: "Action",
    price: 59.99,
    discount: true,
    discountPercent: 25,
    priceFrom: 70,
    star: 5,
    platforms: {
      playstation: true,
      xbox: true,
      nintendo: true,
      pc: true,
    },
    languages: ["English", "Japanese", "French", "German", "Spanish"],
    releaseDate: "2019-03-22",
    playableOn: ["PS5", "PS4", "Xbox One", "PC"],
    editions: {
      deluxe: 79.99,
      complete: 89.99,
      ultimate: 99.99,
    },
    productKey: true,
    available: true,
    stock: 100,
    tags: ["action", "adventure", "samurai"],
    brand: "FromSoftware",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "An amazing combat experience and a challenging journey.",
        date: "2024-11-25T11:00:00Z",
        reviewerName: "Takashi Yamada",
        reviewerEmail: "takashi.yamada@example.com",
      },
    ],
    thumbnail: "/seikro.png",
    images: [
      "/public/seikro1.jpg",
      "/public/seikro2.jpg",
      "/public/seikro3.jpg",
    ],
    video: "https://youtu.be/a2TjEl0l_FU?si=ZcjVkMnlUlnkdQC7",
  },
  {
    name: "Ghostrunner",
    description:
      "A high-speed action game set in a cyberpunk world where players take on the role of a cybernetic ninja fighting through futuristic cityscapes.",
    category: "Action",
    price: 79.99,
    discount: true,
    discountPercent: 25,
    priceFrom: 50,
    star: 4,
    platforms: {
      playstation: true,
      xbox: false,
      nintendo: false,
      pc: true,
    },
    languages: ["English", "Spanish", "French", "German"],
    releaseDate: "2020-10-27",
    playableOn: ["PS5", "PS4", "PC"],
    editions: {
      deluxe: 89.99,
      complete: 109.99,
      ultimate: 129.99,
    },
    productKey: false,
    available: true,
    stock: 150,
    tags: ["cyberpunk", "action", "stealth"],
    brand: "One More Level",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Fast-paced action and a unique setting.",
        date: "2024-11-22T15:00:00Z",
        reviewerName: "Chris Mendez",
        reviewerEmail: "chris.mendez@example.com",
      },
    ],
    thumbnail: "/ghostRunner.png",
    images: ["/ghostRunner1.jpg", "/ghostRunner2.jpg", "/ghostRunner3.jpg"],
  },
  {
    name: "Forza Horizon 6",
    description:
      "An open-world racing game that lets players race across beautiful landscapes, from city streets to sprawling countryside.",
    category: "Racing",
    price: 55.99,
    discount: true,
    discountPercent: 25,
    priceFrom: 40,
    star: 5,
    platforms: {
      playstation: false,
      xbox: true,
      nintendo: true,
      pc: true,
    },
    languages: ["English", "Spanish", "Italian", "German"],
    releaseDate: "2024-10-01",
    playableOn: ["Xbox Series X/S", "PC", "Nintendo Switch"],
    editions: {
      deluxe: 69.99,
      complete: 89.99,
      ultimate: 119.99,
    },
    productKey: true,
    available: true,
    stock: 200,
    tags: ["racing", "open-world", "driving"],
    brand: "Playground Games",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Best racing experience ever!",
        date: "2024-11-23T14:00:00Z",
        reviewerName: "Mark Davis",
        reviewerEmail: "mark.davis@example.com",
      },
    ],
    thumbnail: "/forza.jpg",
    images: [
      "/forza1.jpg",
      "/forza2.jpg",
      "/forza3.jpg",
    ],
  },
  {
    name: "Ghostrunner",
    description:
      "A high-speed action game set in a cyberpunk world where players take on the role of a cybernetic ninja fighting through futuristic cityscapes.",
    category: "Action",
    price: 79.99,
    discount: true,
    discountPercent: 25,
    priceFrom: 50,
    star: 4,
    platforms: {
      playstation: true,
      xbox: false,
      nintendo: false,
      pc: true,
    },
    languages: ["English", "Spanish", "French", "German"],
    releaseDate: "2020-10-27",
    playableOn: ["PS5", "PS4", "PC"],
    editions: {
      deluxe: 89.99,
      complete: 109.99,
      ultimate: 129.99,
    },
    productKey: false,
    available: true,
    stock: 150,
    tags: ["cyberpunk", "action", "stealth"],
    brand: "One More Level",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Fast-paced action and a unique setting.",
        date: "2024-11-22T15:00:00Z",
        reviewerName: "Chris Mendez",
        reviewerEmail: "chris.mendez@example.com",
      },
    ],
    thumbnail: "/ghostRunner.png",
    images: ["/ghostRunner1.jpg", "/ghostRunner2.jpg", "/ghostRunner3.jpg"],
  },
  {
    name: "Forza Horizon 6",
    description:
      "An open-world racing game that lets players race across beautiful landscapes, from city streets to sprawling countryside.",
    category: "Racing",
    price: 55.99,
    discount: true,
    discountPercent: 25,
    priceFrom: 40,
    star: 5,
    platforms: {
      playstation: false,
      xbox: true,
      nintendo: true,
      pc: true,
    },
    languages: ["English", "Spanish", "Italian", "German"],
    releaseDate: "2024-10-01",
    playableOn: ["Xbox Series X/S", "PC", "Nintendo Switch"],
    editions: {
      deluxe: 69.99,
      complete: 89.99,
      ultimate: 119.99,
    },
    productKey: true,
    available: true,
    stock: 200,
    tags: ["racing", "open-world", "driving"],
    brand: "Playground Games",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Best racing experience ever!",
        date: "2024-11-23T14:00:00Z",
        reviewerName: "Mark Davis",
        reviewerEmail: "mark.davis@example.com",
      },
    ],
    thumbnail: "/forza.jpg",
    images: [
      "/forza1.jpg",
      "/forza2.jpg",
      "/forza3.jpg",
    ],
  },
  {
    name: "Sekiro: Shadows Die Once",
    description:
      "A samurai action-adventure game where players control a shinobi on a quest to rescue his kidnapped lord and seek revenge on his enemies.",
    category: "Action",
    price: 59.99,
    discount: true,
    discountPercent: 25,
    priceFrom: 70,
    star: 5,
    platforms: {
      playstation: true,
      xbox: true,
      nintendo: true,
      pc: true,
    },
    languages: ["English", "Japanese", "French", "German", "Spanish"],
    releaseDate: "2019-03-22",
    playableOn: ["PS5", "PS4", "Xbox One", "PC"],
    editions: {
      deluxe: 79.99,
      complete: 89.99,
      ultimate: 99.99,
    },
    productKey: true,
    available: true,
    stock: 100,
    tags: ["action", "adventure", "samurai"],
    brand: "FromSoftware",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "An amazing combat experience and a challenging journey.",
        date: "2024-11-25T11:00:00Z",
        reviewerName: "Takashi Yamada",
        reviewerEmail: "takashi.yamada@example.com",
      },
    ],
    thumbnail: "/seikro.png",
    images: [
      "/public/seikro1.jpg",
      "/public/seikro2.jpg",
      "/public/seikro3.jpg",
    ],
    video: "https://youtu.be/a2TjEl0l_FU?si=ZcjVkMnlUlnkdQC7",
  },
  {
    name: "Ghostrunner",
    description:
      "A high-speed action game set in a cyberpunk world where players take on the role of a cybernetic ninja fighting through futuristic cityscapes.",
    category: "Action",
    price: 79.99,
    discount: true,
    discountPercent: 25,
    priceFrom: 50,
    star: 4,
    platforms: {
      playstation: true,
      xbox: false,
      nintendo: false,
      pc: true,
    },
    languages: ["English", "Spanish", "French", "German"],
    releaseDate: "2020-10-27",
    playableOn: ["PS5", "PS4", "PC"],
    editions: {
      deluxe: 89.99,
      complete: 109.99,
      ultimate: 129.99,
    },
    productKey: false,
    available: true,
    stock: 150,
    tags: ["cyberpunk", "action", "stealth"],
    brand: "One More Level",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Fast-paced action and a unique setting.",
        date: "2024-11-22T15:00:00Z",
        reviewerName: "Chris Mendez",
        reviewerEmail: "chris.mendez@example.com",
      },
    ],
    thumbnail: "/ghostRunner.png",
    images: ["/ghostRunner1.jpg", "/ghostRunner2.jpg", "/ghostRunner3.jpg"],
  },
  {
    name: "Forza Horizon 6",
    description:
      "An open-world racing game that lets players race across beautiful landscapes, from city streets to sprawling countryside.",
    category: "Racing",
    price: 55.99,
    discount: true,
    discountPercent: 25,
    priceFrom: 40,
    star: 5,
    platforms: {
      playstation: false,
      xbox: true,
      nintendo: true,
      pc: true,
    },
    languages: ["English", "Spanish", "Italian", "German"],
    releaseDate: "2024-10-01",
    playableOn: ["Xbox Series X/S", "PC", "Nintendo Switch"],
    editions: {
      deluxe: 69.99,
      complete: 89.99,
      ultimate: 119.99,
    },
    productKey: true,
    available: true,
    stock: 200,
    tags: ["racing", "open-world", "driving"],
    brand: "Playground Games",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Best racing experience ever!",
        date: "2024-11-23T14:00:00Z",
        reviewerName: "Mark Davis",
        reviewerEmail: "mark.davis@example.com",
      },
    ],
    thumbnail: "/forza.jpg",
    images: [
      "/forza1.jpg",
      "/forza2.jpg",
      "/forza3.jpg",
    ],
  },
  {
    name: "Ghostrunner",
    description:
      "A high-speed action game set in a cyberpunk world where players take on the role of a cybernetic ninja fighting through futuristic cityscapes.",
    category: "Action",
    price: 79.99,
    discount: true,
    discountPercent: 25,
    priceFrom: 50,
    star: 4,
    platforms: {
      playstation: true,
      xbox: false,
      nintendo: false,
      pc: true,
    },
    languages: ["English", "Spanish", "French", "German"],
    releaseDate: "2020-10-27",
    playableOn: ["PS5", "PS4", "PC"],
    editions: {
      deluxe: 89.99,
      complete: 109.99,
      ultimate: 129.99,
    },
    productKey: false,
    available: true,
    stock: 150,
    tags: ["cyberpunk", "action", "stealth"],
    brand: "One More Level",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Fast-paced action and a unique setting.",
        date: "2024-11-22T15:00:00Z",
        reviewerName: "Chris Mendez",
        reviewerEmail: "chris.mendez@example.com",
      },
    ],
    thumbnail: "/ghostRunner.png",
    images: ["/ghostRunner1.jpg", "/ghostRunner2.jpg", "/ghostRunner3.jpg"],
  },
  {
    name: "Forza Horizon 6",
    description:
      "An open-world racing game that lets players race across beautiful landscapes, from city streets to sprawling countryside.",
    category: "Racing",
    price: 55.99,
    discount: true,
    discountPercent: 25,
    priceFrom: 40,
    star: 5,
    platforms: {
      playstation: false,
      xbox: true,
      nintendo: true,
      pc: true,
    },
    languages: ["English", "Spanish", "Italian", "German"],
    releaseDate: "2024-10-01",
    playableOn: ["Xbox Series X/S", "PC", "Nintendo Switch"],
    editions: {
      deluxe: 69.99,
      complete: 89.99,
      ultimate: 119.99,
    },
    productKey: true,
    available: true,
    stock: 200,
    tags: ["racing", "open-world", "driving"],
    brand: "Playground Games",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Best racing experience ever!",
        date: "2024-11-23T14:00:00Z",
        reviewerName: "Mark Davis",
        reviewerEmail: "mark.davis@example.com",
      },
    ],
    thumbnail: "/forza.jpg",
    images: [
      "/forza1.jpg",
      "/forza2.jpg",
      "/forza3.jpg",
    ],
  },
  {
    name: "Sekiro: Shadows Die Once",
    description:
      "A samurai action-adventure game where players control a shinobi on a quest to rescue his kidnapped lord and seek revenge on his enemies.",
    category: "Action",
    price: 59.99,
    discount: true,
    discountPercent: 25,
    priceFrom: 70,
    star: 5,
    platforms: {
      playstation: true,
      xbox: true,
      nintendo: true,
      pc: true,
    },
    languages: ["English", "Japanese", "French", "German", "Spanish"],
    releaseDate: "2019-03-22",
    playableOn: ["PS5", "PS4", "Xbox One", "PC"],
    editions: {
      deluxe: 79.99,
      complete: 89.99,
      ultimate: 99.99,
    },
    productKey: true,
    available: true,
    stock: 100,
    tags: ["action", "adventure", "samurai"],
    brand: "FromSoftware",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "An amazing combat experience and a challenging journey.",
        date: "2024-11-25T11:00:00Z",
        reviewerName: "Takashi Yamada",
        reviewerEmail: "takashi.yamada@example.com",
      },
    ],
    thumbnail: "/seikro.png",
    images: [
      "/public/seikro1.jpg",
      "/public/seikro2.jpg",
      "/public/seikro3.jpg",
    ],
    video: "https://youtu.be/a2TjEl0l_FU?si=ZcjVkMnlUlnkdQC7",
  },
  {
    name: "Ghostrunner",
    description:
      "A high-speed action game set in a cyberpunk world where players take on the role of a cybernetic ninja fighting through futuristic cityscapes.",
    category: "Action",
    price: 79.99,
    discount: true,
    discountPercent: 25,
    priceFrom: 50,
    star: 4,
    platforms: {
      playstation: true,
      xbox: false,
      nintendo: false,
      pc: true,
    },
    languages: ["English", "Spanish", "French", "German"],
    releaseDate: "2020-10-27",
    playableOn: ["PS5", "PS4", "PC"],
    editions: {
      deluxe: 89.99,
      complete: 109.99,
      ultimate: 129.99,
    },
    productKey: false,
    available: true,
    stock: 150,
    tags: ["cyberpunk", "action", "stealth"],
    brand: "One More Level",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Fast-paced action and a unique setting.",
        date: "2024-11-22T15:00:00Z",
        reviewerName: "Chris Mendez",
        reviewerEmail: "chris.mendez@example.com",
      },
    ],
    thumbnail: "/ghostRunner.png",
    images: ["/ghostRunner1.jpg", "/ghostRunner2.jpg", "/ghostRunner3.jpg"],
  },
  {
    name: "Forza Horizon 6",
    description:
      "An open-world racing game that lets players race across beautiful landscapes, from city streets to sprawling countryside.",
    category: "Racing",
    price: 55.99,
    discount: true,
    discountPercent: 25,
    priceFrom: 40,
    star: 5,
    platforms: {
      playstation: false,
      xbox: true,
      nintendo: true,
      pc: true,
    },
    languages: ["English", "Spanish", "Italian", "German"],
    releaseDate: "2024-10-01",
    playableOn: ["Xbox Series X/S", "PC", "Nintendo Switch"],
    editions: {
      deluxe: 69.99,
      complete: 89.99,
      ultimate: 119.99,
    },
    productKey: true,
    available: true,
    stock: 200,
    tags: ["racing", "open-world", "driving"],
    brand: "Playground Games",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Best racing experience ever!",
        date: "2024-11-23T14:00:00Z",
        reviewerName: "Mark Davis",
        reviewerEmail: "mark.davis@example.com",
      },
    ],
    thumbnail: "/forza.jpg",
    images: [
      "/forza1.jpg",
      "/forza2.jpg",
      "/forza3.jpg",
    ],
  },
  {
    name: "Ghostrunner",
    description:
      "A high-speed action game set in a cyberpunk world where players take on the role of a cybernetic ninja fighting through futuristic cityscapes.",
    category: "Action",
    price: 79.99,
    discount: true,
    discountPercent: 25,
    priceFrom: 50,
    star: 4,
    platforms: {
      playstation: true,
      xbox: false,
      nintendo: false,
      pc: true,
    },
    languages: ["English", "Spanish", "French", "German"],
    releaseDate: "2020-10-27",
    playableOn: ["PS5", "PS4", "PC"],
    editions: {
      deluxe: 89.99,
      complete: 109.99,
      ultimate: 129.99,
    },
    productKey: false,
    available: true,
    stock: 150,
    tags: ["cyberpunk", "action", "stealth"],
    brand: "One More Level",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Fast-paced action and a unique setting.",
        date: "2024-11-22T15:00:00Z",
        reviewerName: "Chris Mendez",
        reviewerEmail: "chris.mendez@example.com",
      },
    ],
    thumbnail: "/ghostRunner.png",
    images: ["/ghostRunner1.jpg", "/ghostRunner2.jpg", "/ghostRunner3.jpg"],
  },
  {
    name: "Forza Horizon 6",
    description:
      "An open-world racing game that lets players race across beautiful landscapes, from city streets to sprawling countryside.",
    category: "Racing",
    price: 55.99,
    discount: true,
    discountPercent: 25,
    priceFrom: 40,
    star: 5,
    platforms: {
      playstation: false,
      xbox: true,
      nintendo: true,
      pc: true,
    },
    languages: ["English", "Spanish", "Italian", "German"],
    releaseDate: "2024-10-01",
    playableOn: ["Xbox Series X/S", "PC", "Nintendo Switch"],
    editions: {
      deluxe: 69.99,
      complete: 89.99,
      ultimate: 119.99,
    },
    productKey: true,
    available: true,
    stock: 200,
    tags: ["racing", "open-world", "driving"],
    brand: "Playground Games",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Best racing experience ever!",
        date: "2024-11-23T14:00:00Z",
        reviewerName: "Mark Davis",
        reviewerEmail: "mark.davis@example.com",
      },
    ],
    thumbnail: "/forza.jpg",
    images: [
      "/forza1.jpg",
      "/forza2.jpg",
      "/forza3.jpg",
    ],
  },
];
